FROM node:14-buster

VOLUME /home/node

ENV NPM_CONFIG_PREFIX=/home/node/.npm-global
ENV PATH="${PATH}:/home/node/.npm-global/bin"

RUN apt-get update \
  && apt-get install -y nano

USER node

RUN npm install n8n -g
